// TODO: Create a 2 tab view for the page
// 1. Create a container that has 2 tabs
// 2. Create a tab for the privacy policy
// 3. Create a tab for the terms of service

import PageContainer from "@/components/layout/PageContainer";
import theme from "@/styles/theme";
import {
  Box,
  ChakraProvider,
  Heading,
  List,
  ListItem,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
  UnorderedList,
} from "@chakra-ui/react";
import React, { FunctionComponent } from "react";

// Convert this pages headings and Text components to have the "policy" variant
const PolicyTabs = () => {
  return (
    <ChakraProvider theme={theme}>
      <PageContainer>
        <Tabs>
          <TabList>
            <Tab>Privacy Policy</Tab>
            <Tab>Refund Policy</Tab>
            <Tab>Terms of Service</Tab>
          </TabList>

          <TabPanels>
            <TabPanel>
              <PrivacyPolicy />
            </TabPanel>
            <TabPanel>
              <RefundPolicy />
            </TabPanel>
            <TabPanel>
              <TermsOfService />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </PageContainer>
    </ChakraProvider>
  );
};

const PrivacyPolicy = () => (
  <Box mt={10}>
    <Heading>Privacy Policy</Heading>
    <Text mt={"20px"}>
      PetPics.ai is committed to protecting your privacy. This privacy policy
      explains how we collect, use, and share information about you when you use
      our website, mobile application, and other online services.
    </Text>
    <Text mt={"20px"}>
      By using the Services, you agree to the collection, use, and sharing of
      your information as described in this Policy. If you do not agree with our
      policies and practices, do not use the Services.
    </Text>

    <Heading variant="policy" as="h2" size="md">
      How We Use Your Information
    </Heading>
    <Text mt={"20px"}>We use your information for the following purposes:</Text>

    <UnorderedList mt={"30px"}>
      <ListItem>
        Email: For login information, account services, and optional updates on
        the status of your purchases.
      </ListItem>
      <ListItem>Images: Solely to create a model of your pet.</ListItem>
    </UnorderedList>

    <Heading variant="policy" as="h2" size="md">
      Data Retention
    </Heading>
    <Text mt={"20px"}>
      We will retain your information for as long as your account is active or
      as needed to provide you with the Services. We may also retain your
      information for research and analytics purposes.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Data Security
    </Heading>
    <Text mt={"20px"}>
      We have implemented measures to protect the security of your information.
      However, no method of transmission over the internet or method of
      electronic storage is completely secure, and we cannot guarantee the
      absolute security of your information.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Children's Privacy
    </Heading>
    <Text mt={"20px"}>
      The Services are not intended for children under the age of 13. We do not
      knowingly collect personal information from children under the age of 13.
      If we become aware that we have collected personal information from a
      child under the age of 13, we will take steps to delete the information as
      soon as possible.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Changes to This Policy
    </Heading>
    <Text mt={"20px"}>
      We may update this Policy from time to time. We will post any changes on
      this page and encourage you to review the Policy periodically. If we make
      material changes to the Policy, we will notify you by email or through the
      Services.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Contact Us
    </Heading>
    <Text mt={"20px"}>
      If you have any questions about this Policy, please contact us at
      support@petpics.ai.
    </Text>
  </Box>
);

const RefundPolicy = () => (
  <Box mt={10}>
    <Heading>Refund Policy</Heading>
    <Text mt={"20px"}>
      Thank you for using PetPics.ai to create unique and personalized AI art of
      your pets. We are dedicated to providing high-quality products and
      services to our customers. However, due to the nature of our services, we
      are unable to offer refunds.
    </Text>
    <Text mt={"20px"}>
      {" "}
      All sales of AI art generated by PetPics.ai are final and non-refundable.
      This includes, but is not limited to, cases where:
    </Text>
    <UnorderedList mt={"30px"} ml={"40px"}>
      <ListItem>You are not satisfied with the quality of the AI art</ListItem>
      <ListItem>
        You do not receive the AI art within the expected delivery time
      </ListItem>
      <ListItem>
        You experience technical difficulties with our website
      </ListItem>
    </UnorderedList>{" "}
    <Text mt={"20px"}>
      Please make sure that you have carefully reviewed your order prior to
      finalizing your purchase. If you have any questions or concerns about our
      products or services, please contact us at support@petpics.ai before
      placing your order. Thank you for your understanding.
    </Text>
    <Text mt={"20px"}>Best regards,</Text>
    <Text mt={"20px"}>PetPics Team</Text>
  </Box>
);
export default PolicyTabs;

const TermsOfService = () => (
  <Box mt={10}>
    <Heading>Terms of Service</Heading>
    <Text mt={"20px"}>
      Welcome to PetPics.ai. By accessing or using the Website, you agree to be
      bound by these terms and conditions. If you do not agree to all of the
      Terms, please do not use the Website.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Use of the Website
    </Heading>
    <Text mt={"20px"}>
      The Website is for personal and non-commercial use only. You may not use
      the Website for any illegal or unauthorized purpose. You may not use the
      Website in any manner that could damage, disable, overburden, or impair
      the Website or interfere with any other party's use of the Website.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      User Generated Content
    </Heading>
    <Text mt={"20px"}>
      The Website may allow users to post, upload, or submit content (including,
      but not limited to, photos, images, and text). By posting, uploading, or
      submitting User Generated Content to the Website, you represent and
      warrant that you have the right to do so and that the User Generated
      Content does not violate any laws or the rights of any third party.
    </Text>
    <Text mt={"20px"}>
      You understand and agree that PetPics.ai has the right, but not the
      obligation, to review, edit, or delete any User Generated Content that it
      determines, in its sole discretion, violates these Terms or is otherwise
      inappropriate.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Intellectual Property
    </Heading>
    <Text mt={"20px"}>
      The Website and all content and materials on the Website, including, but
      not limited to, text, graphics, images, and software, are the property of
      PetPics.ai or its licensors and are protected by copyright and trademark
      laws. You may not use any content or materials on the Website for any
      commercial purpose without the express written consent of PetPics.ai.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Disclaimer of Warranties
    </Heading>
    <Text mt={"20px"}>
      The Website is provided on an "as is" and "as available" basis. PetPics.ai
      makes no representations or warranties of any kind, express or implied, as
      to the operation of the Website or the information, content, materials, or
      products included on the Website. PetPics.ai does not warrant that the
      Website will be uninterrupted or error-free.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Limitation of Liability
    </Heading>
    <Text mt={"20px"}>
      PetPics.ai will not be liable for any damages of any kind arising from the
      use of the Website, including, but not limited to, direct, indirect,
      incidental, punitive, and consequential damages.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Indemnification
    </Heading>
    <Text mt={"20px"}>
      You agree to indemnify and hold PetPics.ai and its affiliates, officers,
      agents, and employees harmless from any claim or demand, including
      reasonable attorneys' fees, made by any third party due to or arising out
      of your use of the Website, your violation of these Terms, or your
      violation of any rights of another.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Governing Law
    </Heading>
    <Text mt={"20px"}>
      These Terms and your use of the Website will be governed by and construed
      in accordance with the laws of the state of Texas, without giving effect
      to any principles of conflicts of law.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Dispute Resolution
    </Heading>
    <Text mt={"20px"}>
      Any dispute arising out of or relating to these Terms or the Website will
      be resolved through binding arbitration in accordance with the Commercial
      Arbitration Rules of the American Arbitration Association. The arbitration
      will be conducted in the state of Texas.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Changes to the Terms
    </Heading>
    <Text mt={"20px"}>
      PetPics.ai reserves the right to update or modify these Terms at any time
      without prior notice. Your continued use of the Website after any changes
      to the Terms are posted will be considered acceptance of those changes.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Entire Agreement
    </Heading>
    <Text mt={"20px"}>
      These Terms constitute the entire agreement between you and PetPics.ai and
      govern your use of the Website, superseding any prior agreements between
      you and PetPics.ai.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Severability
    </Heading>
    <Text mt={"20px"}>
      If any part of these Terms is found to be invalid or unenforceable, that
      part will be enforced to the maximum extent permissible, and the remainder
      of the Terms will remain in full force and effect.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Waiver
    </Heading>
    <Text mt={"20px"}>
      The failure of PetPics.ai to exercise or enforce any right or provision of
      these Terms will not constitute a waiver of such right or provision.
    </Text>
    <Heading variant="policy" as="h2" size="md">
      Contact Us
    </Heading>
    <Text mt={"20px"}>
      If you have any questions about these Terms, please contact us at
      support@petpics.ai.
    </Text>
    <Text mt={"20px"}>Thank you for using PetPics.ai.</Text>
    <Text mt={"20px"}>Last updated: 1/9/2023</Text>
  </Box>
);
